### PR TITLE
<feat>:more pages

### LINKED ISSUE #4: Build wireframes for remaining pages
login page wireframe for admin and citizen with responsive designs
 Profile page wireframe for admin and citizen with responsive designs

### LINKED ISSUE #5: login page

### LINKED ISSUE #6: Register page

### LINKED ISSUE #7: Footer
complete the footer

### PR DESCRIPTION
**Pull request by sleekLancelot**
Fixed the footer after receiving the design,
New login page,
Register page.

### CODE REVIEW

**Comment by Timmymichael** [comment]
Complete wire-frame of the User's Profile page.
Dashboard(User)- with uploaded picture
Dashboard(User)- with completed Profile Page

**Comment by udofia2** [comment]
Nice design. Matches the backend Schema

**Review by udofia2 — APPROVED** [review]
lovely design

**Comment by Timmymichael** [comment]
I'm glad it matched it.

**Pull request merged**
